# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-06 03:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0003_projects_article_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='link',
            field=models.SlugField(null=True),
        ),
    ]
