# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-06 03:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0004_projects_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='link',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
